import matplotlib.pyplot as plt
from matplotlib.backend_bases import MouseEvent
from typing import TypeVar, Generic
import splines

SplineType = TypeVar('SplineType', bound=splines.BaseSpline)
# SplineEditor, enables click and drag editing of knots, visualization of the series of knots and of the path generated by them
class SplineEditor(Generic[SplineType]):
    """click and drag spline knot editor"""
    def __init__(self, spline: SplineType):
        self.figure = None
        self.axis = None
        self.line = None
        self.interpolant = splines.Interpolant(spline)


    